[package]
name = "taki-cli"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "CLI for my workspace."
homepage = "https://github.com/takimoysha/taki-cli"
repository = "https://github.com/takimoysha/taki-cli"
readme = "README.md"

[dependencies]
anyhow = "1.0.79"
clap = "4.4.18"
